name: Build
on: [ push, pull_request ]
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      
    - name: Set Permissions
      run: chmod +x ./gradlew
    
    - name: Execute Gradle build
      run: ./gradlew build
      
    - name: capture build artifacts
      if: ${{ runner.os == 'Linux' }} # Only upload artifacts built from latest java on one OS
      uses: actions/upload-artifact@v2
      with:
        name: Artifacts
        path: |
          build/libs/MCXR-Installer-2.0.4.jar
          build/libs/MCXR-Installer-2.0.4.exe
        
